# Generated by Django 4.1.5 on 2023-01-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
