# Generated by Django 4.1.5 on 2023-01-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
    ]
