# Generated by Django 4.1.5 on 2023-01-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_remove_membership_membership_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
